site_name: obia
site_url: https://github.com/iosefa/obia
repo_url: https://github.com/iosefa/obia

theme:
    name: material
    palette:
        primary: green
        accent: deep-orange
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
    custom_dir: overrides

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
        include_source: true
        execute: false
        ignore_h1_titles: true

markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

nav:
    - Home: index.md
    - Installation: installation.md
    - Quickstart: quickstart.md
    - Project Structure: project-structure.md
    - Workflows: workflows.md
    - Examples:
        - Segmentation Quickstart: examples/segmentation-quickstart.ipynb
    - Project Status: status.md
    - Contributing: contributing.md
    - Changelog: https://github.com/iosefa/obia/releases
    - Report Issues: https://github.com/iosefa/obia/issues
    - API Reference:
        - Overview: api/index.md
        - Handlers: api/handlers.md
        - Segmentation: api/segmentation.md
        - Detection: api/detection.md
        - Classification: api/classification.md
        - Utils: api/utils.md

extra_css:
    - overrides/custom.css

extra_javascript:
 - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
