site_name: pyMobia
site_url: https://pymobia.sefa.ai
repo_url: https://github.com/iosefa/pymobia

theme:
    name: material
    palette:
        primary: green
        accent: deep-orange
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
    custom_dir: overrides

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
        include_source: true
        execute: false
        ignore_h1_titles: true

markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage:
        - usage/getting-started.md
        - usage/segmentation.md
        - usage/feature-building.md
        - usage/classification.md
        - usage/feature-importance.md
        - usage/uncertainty-analysis.md
        - usage/working-with-big-data.md
    - Contributing: contributing.md
    - Changelog: https://github.com/iosefa/pymobia/releases
    - Report Issues: https://github.com/iosefa/pymobia/issues
    - Examples:
        - examples/getting-started.ipynb
    - API Reference:
        - calculate module: api/calculate.md
        - filters module: api/filters.md
        - handlers module: api/handlers.md
        - pipeline module: api/pipeline.md
        - process module: api/process.md
        - visualize module: api/visualize.md

extra_css:
    - overrides/custom.css

extra_javascript:
 - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js